
CC = gcc
CFLAGS = -Wall

TARGET = main
$(TARGET): main.o datos.o calculos.o
	$(CC) $(CFLAGS) -o $(TARGET) main.o datos.o calculos.o

main.o: main.c datos.h calculos.h
	$(CC) $(CFLAGS) -c main.c

datos.o: datos.c datos.h
	$(CC) $(CFLAGS) -c datos.c

calculos.o: calculos.c calculos.h
	$(CC) $(CFLAGS) -c calculos.c

clean:
	rm -f *.o *.s $(TARGET)